name: Python Code Quality
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint autopep8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Check for Python files
      id: check-py-files
      run: |
        PY_FILES=$(git ls-files '*.py')
        if [ -n "$PY_FILES" ]; then
          echo "HAS_PY_FILES=true" >> $GITHUB_OUTPUT
          echo "PY_FILES=$PY_FILES" >> $GITHUB_OUTPUT
        else
          echo "HAS_PY_FILES=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Analyze code with pylint
      if: steps.check-py-files.outputs.HAS_PY_FILES == 'true'
      run: |
        pylint --fail-under=7.0 ${{ steps.check-py-files.outputs.PY_FILES }}
      continue-on-error: true
    
    - name: Format code with autopep8
      if: steps.check-py-files.outputs.HAS_PY_FILES == 'true'
      run: |
        autopep8 --in-place --aggressive --aggressive ${{ steps.check-py-files.outputs.PY_FILES }}
    
    - name: Commit changes
      if: steps.check-py-files.outputs.HAS_PY_FILES == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Auto-format Python code with autopep8" || true
